/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_healthz_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/gateway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Gateway */
        get: operations["health_gateway_healthz_gateway_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Specs */
        get: operations["list_specs_specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specs/{spec_code}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spec */
        get: operations["get_spec_specs__spec_code___version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_batches__batch_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_no}/master-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Master Parameters */
        get: operations["master_parameters_batches__batch_no__master_parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Register */
        get: operations["register_register_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oos */
        get: operations["oos_oos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_templates_get"];
        put?: never;
        /** Upload Template */
        post: operations["upload_template_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{doc_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List For Type */
        get: operations["list_for_type_templates__doc_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Labs */
        get: operations["labs_labs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parameters */
        get: operations["parameters_parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Batch */
        Batch: {
            /** Production Batch Number */
            production_batch_number: string;
            /** Product Name */
            product_name: string;
            /** Strain */
            strain?: string | null;
            /** Dominance */
            dominance?: string | null;
            /** Grade */
            grade?: string | null;
            /** Grade Designation */
            grade_designation?: string | null;
            /** Spec Code */
            spec_code?: string | null;
            /** Spec Version */
            spec_version?: string | null;
            /** Spec Reference */
            spec_reference?: string | null;
            /** Status */
            status: string;
            /** Production Date */
            production_date?: string | null;
            /** Quantity Kg */
            quantity_kg?: number | null;
            lineage: components["schemas"]["LineageRef"];
        };
        /** BatchSummary */
        BatchSummary: {
            /** Production Batch Number */
            production_batch_number: string;
            /** Packaging Batch Number */
            packaging_batch_number?: string | null;
            /** Product Name */
            product_name: string;
            /** Dominance */
            dominance?: string | null;
            /** Grade */
            grade?: string | null;
            /** Grade Designation */
            grade_designation?: string | null;
            /** Spec Reference */
            spec_reference?: string | null;
            /** Status */
            status: string;
            /**
             * Params Total
             * @default 0
             */
            params_total: number;
            /**
             * Params Conforming
             * @default 0
             */
            params_conforming: number;
            /**
             * Params Pending
             * @default 0
             */
            params_pending: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /**
             * Batches In Testing
             * @default 0
             */
            batches_in_testing: number;
            /**
             * Ecoa Pending Review
             * @default 0
             */
            ecoa_pending_review: number;
            /**
             * Coqs Issued This Year
             * @default 0
             */
            coqs_issued_this_year: number;
            /**
             * Open Oos
             * @default 0
             */
            open_oos: number;
            /**
             * Recent Documents
             * @default []
             */
            recent_documents: components["schemas"]["DocumentRef"][];
            /**
             * Recent Batches
             * @default []
             */
            recent_batches: components["schemas"]["BatchSummary"][];
        };
        /** DbHealth */
        DbHealth: {
            /** Connected */
            connected: boolean;
            /** Server Version */
            server_version?: string | null;
            /** Tables */
            tables?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * DocumentRef
         * @description A source certificate (iCoA/eCoA) in feeds and ingestion lists.
         */
        DocumentRef: {
            /** Document Code */
            document_code: string;
            /**
             * Cert Type
             * @default eCoA
             */
            cert_type: string;
            /**
             * Doc Type
             * @default cannabis_coa
             */
            doc_type: string;
            /** Institution Name */
            institution_name?: string | null;
            /** Lab Code */
            lab_code?: string | null;
            /** Batch Number */
            batch_number?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Register Status */
            register_status?: string | null;
            /** Extraction Confidence */
            extraction_confidence?: number | null;
        };
        /**
         * DocumentTemplate
         * @description A versioned template for a document the app GENERATES (iCoA/CoQ/CoA/Spec).
         */
        DocumentTemplate: {
            /** Doc Type */
            doc_type: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Doc Class
             * @default flower_coq
             */
            doc_class: string;
            /**
             * Render Engine
             * @default weasyprint
             */
            render_engine: string;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * IngestAccepted
         * @description Phase 0 stub response for an accepted ingest request.
         */
        IngestAccepted: {
            /** Received */
            received: number;
            /**
             * Document Codes
             * @default []
             */
            document_codes: string[];
            /**
             * Note
             * @default Phase 0 stub: OCR/parse/embed + agent extraction land in Phase 1-2.
             */
            note: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Batch Hint */
            batch_hint?: string | null;
            /**
             * Filenames
             * @default []
             */
            filenames: string[];
        };
        /** LabInstitution */
        LabInstitution: {
            /** Lab Code */
            lab_code?: string | null;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Credentials */
            credentials?: string | null;
            /** Default Language */
            default_language?: string | null;
        };
        /** LineageRef */
        LineageRef: {
            /** Cultivation Batch Number */
            cultivation_batch_number?: string | null;
            /** Production Batch Number */
            production_batch_number: string;
            /**
             * Packaging Batch Numbers
             * @default []
             */
            packaging_batch_numbers: string[];
        };
        /**
         * MasterParameterLine
         * @description Single source-of-truth parameter row for the Batch Record + COQ lines.
         */
        MasterParameterLine: {
            /** Canonical Key */
            canonical_key?: string | null;
            /** Param Name */
            param_name: string;
            /** Method */
            method?: string | null;
            /** Acceptance Text */
            acceptance_text?: string | null;
            /** Result Display */
            result_display?: string | null;
            /** Unit */
            unit?: string | null;
            /**
             * Verdict
             * @default pending
             */
            verdict: string;
            /** Source Institution Name */
            source_institution_name?: string | null;
            /** Source Lab Code */
            source_lab_code?: string | null;
            /** Source Document Code */
            source_document_code?: string | null;
            /** Source Document Date */
            source_document_date?: string | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * OOSItem
         * @description An out-of-specification result blocking CoQ issuance (OOS/NCR view).
         */
        OOSItem: {
            /** Batch No */
            batch_no?: string | null;
            /** Canonical Key */
            canonical_key?: string | null;
            /** Param Name */
            param_name: string;
            /** Result Display */
            result_display?: string | null;
            /** Acceptance Text */
            acceptance_text?: string | null;
            /** Source Document Code */
            source_document_code?: string | null;
            /**
             * Status
             * @default open
             */
            status: string;
        };
        /** ParameterDictionaryEntry */
        ParameterDictionaryEntry: {
            /** Canonical Key */
            canonical_key: string;
            /** Display Name */
            display_name: string;
            /** Category */
            category: string;
            /** Canonical Unit */
            canonical_unit?: string | null;
            /** Default Method Family */
            default_method_family?: string | null;
            /** Default Source */
            default_source?: string | null;
        };
        /** ProductSpec */
        ProductSpec: {
            /** Spec Code */
            spec_code: string;
            /** Version */
            version: string;
            /**
             * Category
             * @description IMG | IPM | FP | IMB
             */
            category: string;
            /** Title */
            title: string;
            /**
             * Dominance
             * @description THC | CBD (strain-agnostic)
             */
            dominance?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Effective From */
            effective_from?: string | null;
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["SpecParameter"][];
            /**
             * Grades
             * @default []
             */
            grades: components["schemas"]["SpecGrade"][];
        };
        /**
         * RegisterEntry
         * @description Certificate Issuance Register row (iCoA/eCoA/CoQ) — QCSOP 012 v3.
         */
        RegisterEntry: {
            /** Cert Type */
            cert_type: string;
            /** Certificate Number */
            certificate_number: string;
            /** Seq No */
            seq_no?: number | null;
            /** Year */
            year?: number | null;
            /** Batch No */
            batch_no?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Spec Ref */
            spec_ref?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Prepared By */
            prepared_by?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Status */
            status: string;
            /** Oos Ref */
            oos_ref?: string | null;
            /** Archive Ref */
            archive_ref?: string | null;
        };
        /** SpecGrade */
        SpecGrade: {
            /** Grade */
            grade: string;
            /** Designation */
            designation?: string | null;
            /** Product Code */
            product_code?: string | null;
            /** Thc Low */
            thc_low?: number | null;
            /** Thc High */
            thc_high?: number | null;
            /** Cbd Max */
            cbd_max?: number | null;
        };
        /** SpecParameter */
        SpecParameter: {
            /** Display Order */
            display_order?: number | null;
            /** Param Name */
            param_name: string;
            /** Method */
            method?: string | null;
            /** Operator */
            operator?: string | null;
            /** Limit Low */
            limit_low?: number | null;
            /** Limit High */
            limit_high?: number | null;
            /** Limit Text */
            limit_text?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /**
         * TemplateUpload
         * @description Upload a new template version; supersedes the prior active for its doc_type.
         */
        TemplateUpload: {
            /** Doc Type */
            doc_type: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Html */
            html: string;
            /**
             * Doc Class
             * @default flower_coq
             */
            doc_class: string;
            /**
             * Render Engine
             * @default weasyprint
             */
            render_engine: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    health_db_healthz_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbHealth"];
                };
            };
        };
    };
    health_gateway_healthz_gateway_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_specs_specs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSpec"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spec_specs__spec_code___version__get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path: {
                spec_code: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_batches_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_batches__batch_no__get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path: {
                batch_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    master_parameters_batches__batch_no__master_parameters_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path: {
                batch_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterParameterLine"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oos_oos_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OOSItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_templates_get: {
        parameters: {
            query?: {
                include_superseded?: boolean;
            };
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_template_templates_post: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_for_type_templates__doc_type__get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path: {
                doc_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    labs_labs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabInstitution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parameters_parameters_get: {
        parameters: {
            query?: never;
            header?: {
                "x-coqgen-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterDictionaryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
